### ISSUE TITLE
Add Meta Tags

### ISSUE THREAD

**Issue by 1stdevfriend** [koders-in/Portfolio#11]
Meta tags and content can be added for improvising SEO

**Comment by shikharcodes** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Smodi16** [comment]
Done :)

**Comment by shikharcodes** [comment]
> Good work! Feel free to apply at [info@koders.in](mailto:info@koders.in) in case if you are looking for a position as an SDE intern

Thank you @1stdevfriend, I will surely contact soon!
