### ISSUE TITLE
Export method for component and pages

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Portfolio#13]
- [ ] export all components from a single file
- [ ] export all pages from a single file

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by 1stdevfriend** [comment]
Sure. Go ahead. Assigned it to you.

**Comment by amit-ksh** [comment]
I'd like to work on this issue. Please assign this to me.

**Comment by 1stdevfriend** [comment]
Sure @amit-ksh
