### ISSUE TITLE
CSS optimization

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Portfolio#15]
- [ ] use CSS variable for color pallet
- [ ] custom scrollbar matches with our theme

**Comment by Hariprasad19036** [comment]
I would like to work on this issue, kindly assign this to me!

**Comment by 1stdevfriend** [comment]
Done :) @Hariprasad19036

**Comment by 1stdevfriend** [comment]
@Hariprasad19036

**Comment by Hariprasad19036** [comment]
Apologies for not being able to take up this issue!

**Comment by 1stdevfriend** [comment]
Oh no problem.
