### ISSUE TITLE
Upload docker image

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Portfolio#27]
- [x] Upload Docker image on GitHub actions.

**Comment by shikharcodes** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by 1stdevfriend** [comment]
This one has already been done by one of the members. You can look for others :) @shikharcodes

**Comment by 1stdevfriend** [comment]
Fixed at dfdc75c6d4af23fc4120db4c179e87868a0463dc
