### ISSUE TITLE
Prettier config file missing

### ISSUE THREAD

**Issue by FireeagSaini** [koders-in/Portfolio#32]
### What is the issue?

Nowadays everyone uses [Prettier](https://prettier.io/), An automated code formatting tool.

The issue is everyone have different **global settings** of prettier according to their style. BUT this can **cause useless changes** to opensource projects as many people works on same code.

So having a `prettier config file` inside project directory can resolve this issue.

### How to solve this issue?

adding a file `.prettierrc` and `.prettierignore` will solve this issue

**Comment by FireeagSaini** [comment]
merge #33 to close this issue.

**Comment by 1stdevfriend** [comment]
Hey hi @FireeagSaini. 
Adding a generic prettier config file isn't required at the moment. Can you please look into other issues and try to resolve those?

**Comment by FireeagSaini** [comment]
As you wish @1stdevfriend
