### ISSUE TITLE
Redundant icon 

### ISSUE THREAD

**Issue by 1stdevfriend** [koders-in/Portfolio#4]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/27912312/187952075-8fa0175d-06bb-4a51-a01f-da6cb7499188.png">

**Comment by 1stdevfriend** [comment]
![image](https://user-images.githubusercontent.com/27912312/190970387-917f457d-f8ad-4b55-873d-3cfd7bb385dd.png)

**Comment by valasubramanian-tw** [comment]
@1stdevfriend Do you want to replace Satisfaction image with another image?
If so, you can assign it to me. I will work on this issue. thanks.

**Comment by 1stdevfriend** [comment]
Yes. Sure.

**Comment by valasubramanian-tw** [comment]
@1stdevfriend **/icon3.png** is used as image for Satisfaction. Can you provide the alternate image file name to replace that?

<img width="385" alt="Screenshot 2022-10-16 at 4 31 45 PM" src="https://user-images.githubusercontent.com/110656887/196031667-8c6e40b9-56af-47ec-8c8c-f610a79265f7.png">

**Comment by 1stdevfriend** [comment]
That's what you have to do haha

**Comment by valasubramanian-tw** [comment]
> That's what you have to do haha

My assumption was you will provide alternate image file which I will replace in the source code. Since I'm a programmer I don't know to design or create images. So you can unassign me from this issue. thanks.

**Comment by 1stdevfriend** [comment]
Changing logo path won't be an real issue over hacktoberfest, I believe. Looks like you misunderstood the requirements.
